name: Update document

on:
  pull_request:
    branches:
      - master
      - develop
    types: [closed]

jobs:
  greet:
    runs-on: windows-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DocFX
        shell: cmd
        run: |
          choco install docfx -y
          cd docFX
          update.bat
          
      - name: Push
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docs